apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
 name: myapp-vpa
spec:
 targetRef:
   apiVersion: "apps/v1"
   kind:      Deployment
   name:      myapp
 updatePolicy:
   updateMode: "Off"
